/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.view.form;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import root.domain.Iznajmljivanje;
import root.domain.Korisnik;
import root.domain.Zaposleni;
import root.kontroler.Kontroler;
import root.niti.OsveziNit;
import root.view.form.komponente.tabele.ModelTabeleIznajmljivanjaKorisnika;
import root.view.form.komponente.tabele.ModelTabeleKorisnici;

/**
 *
 * @author Bane
 */
public class FrmKorisnikPretraga extends javax.swing.JFrame {
    
    private Zaposleni ulogovaniZ;

    public Zaposleni getZaposleni() {
        return ulogovaniZ;
    }

    public void setZaposleni(Zaposleni zaposleni) {
        this.ulogovaniZ = zaposleni;
    }

    /**
     * Creates new form FrmKorisnikPretraga
     */
    public FrmKorisnikPretraga() {
        super("Pretraga korisnika");
        initComponents();
        OsveziNit on = new OsveziNit(this);
        on.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaKorisnici = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga korisnika");

        tabelaKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaKorisnici);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jButton2.setText("Otkazi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Filter: ");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDodaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnIzmeni)
                    .addComponent(btnDodaj))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
    
           if(tabelaKorisnici.getSelectedRow()==-1){
               JOptionPane.showMessageDialog(this, "Morate selektovati korisnika u tabeli!","Izmena korisnika",JOptionPane.ERROR_MESSAGE);
           }
           
           int red = tabelaKorisnici.getSelectedRow();
           int pravired = tabelaKorisnici.convertRowIndexToModel(red);
           
           if(pravired!=-1){
           ModelTabeleKorisnici mtk = (ModelTabeleKorisnici) tabelaKorisnici.getModel();
           Korisnik izabraniKorisnik = mtk.dajIzabranogKorisnika(pravired);
           FrmKorisnikIzmena fki = new FrmKorisnikIzmena(this, true);
           fki.srediTabelu();
           fki.srediFormu(izabraniKorisnik);
           fki.setLocationRelativeTo(this);
           fki.pack();
           fki.setZaposleni(ulogovaniZ);
           fki.setVisible(true);
           }
         
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String query = txtPretraga.getText();
        filtrirajTabelu(query);
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        FrmKorisnik frk = new FrmKorisnik(this, true);
        frk.setLocationRelativeTo(this);
        frk.pack();
        frk.setZaposleni(ulogovaniZ);
        frk.setVisible(true);
    }//GEN-LAST:event_btnDodajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaKorisnici;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables
  
    public void srediTabelu() {
        List<Korisnik> korisnici = Kontroler.getInstance().vratiSveKorisnike();
        ModelTabeleKorisnici mtk = new ModelTabeleKorisnici(korisnici);
        tabelaKorisnici.setModel(mtk);
        
    }

    private void filtrirajTabelu(String query) {
        ModelTabeleKorisnici mtk = (ModelTabeleKorisnici) tabelaKorisnici.getModel();
        TableRowSorter<AbstractTableModel> tr = new TableRowSorter<AbstractTableModel>(mtk);
        tabelaKorisnici.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));

    }


  
}
