/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package root.view.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import root.domain.Iznajmljivanje;
import root.domain.Korisnik;
import root.domain.Zaposleni;
import root.kontroler.Kontroler;
import root.view.form.komponente.tabele.ModelTabeleIznajmljivanja;
import root.view.form.komponente.tabele.ModelTabeleIznajmljivanjaKorisnika;

/**
 *
 * @author Bane
 */
public class FrmKorisnikIzmena extends javax.swing.JDialog {
    
    private Zaposleni ulogovaniZ;

    public Zaposleni getZaposleni() {
        return ulogovaniZ;
    }

    public void setZaposleni(Zaposleni zaposleni) {
        this.ulogovaniZ = zaposleni;
    }

    /**
     * Creates new form FrmKorisnikIzmena
     */
    public FrmKorisnikIzmena(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBrLicne = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaIznajmljivanjKorisnika = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena korisnika");

        jLabel1.setText("Broj licne karte: ");

        jLabel2.setText("Ime: ");

        jLabel3.setText("Prezime: ");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        tabelaIznajmljivanjKorisnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaIznajmljivanjKorisnika);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                            .addComponent(txtIme)
                            .addComponent(txtBrLicne))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)
                        .addGap(18, 18, 18)
                        .addComponent(btnOtkazi)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBrLicne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOtkazi))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
      dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
       Korisnik k = dajKorinsika();
       
        if(txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Greska prilikom izmene!\n" , "Izmena korisnika", JOptionPane.ERROR_MESSAGE);
           return;
       }
        
        try {
            Kontroler.getInstance().izmeniKorisnika(k);
            JOptionPane.showMessageDialog(this, "Korisnik uspesno izmenjen!\n", "Izmena korisnika", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom izmene!\n" + ex.getMessage(), "Izmena korisnika", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FrmKorisnikIzmena.class.getName()).log(Level.SEVERE, null, ex);

        }
           
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaIznajmljivanjKorisnika;
    private javax.swing.JTextField txtBrLicne;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    void srediFormu(Korisnik izabraniKorisnik) {
        txtBrLicne.setText(izabraniKorisnik.getBrojLicneKarte());
        txtIme.setText(izabraniKorisnik.getImeKorisnika());
        txtPrezime.setText(izabraniKorisnik.getPrezimeKorisnika());
        txtBrLicne.setEditable(false);
    }

    private Korisnik dajKorinsika() {
        Korisnik korisnik = new Korisnik();
        korisnik.setBrojLicneKarte(txtBrLicne.getText().trim());
        korisnik.setImeKorisnika(txtIme.getText().trim());
        korisnik.setPrezimeKorisnika(txtPrezime.getText().trim());
        korisnik.setZaposleni(getZaposleni());
        return korisnik;
    }
    
        public void srediTabelu() {
        Korisnik k = dajKorinsika();    
        List<Iznajmljivanje> iznajmljivanja = Kontroler.getInstance().vratiSvaIznajmljivanja();
        for (Iznajmljivanje iznam : iznajmljivanja) {
               
                    for (int i = 0; i < iznajmljivanja.size(); i++) {
                        if(!(iznam.getKorisnik().getBrojLicneKarte().equals(k.getBrojLicneKarte()))){
                            iznajmljivanja.remove(i);
                        }
                        
                    }
                
            }
            ModelTabeleIznajmljivanjaKorisnika mtik = new ModelTabeleIznajmljivanjaKorisnika(iznajmljivanja);
            tabelaIznajmljivanjKorisnika.setModel(mtik);
    }
}
